name: Deploy-mkdocs-gh-pages

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md



jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        pip3 install pipenv
        pipenv install
        pipenv run python3 ./update.py

    - run: pipenv run mkdocs build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./site
